language: go
arch: ppc64le
os: linux
dist: bionic
env:
  - IMAGE_REPO=localhost:5000
go:
  - "1.13.3"
go_import_path: github.com/GoogleContainerTools/kaniko

jobs:
  include:
    - name: unit-test
      script:
        - make test
    - name: integration-test-run
      before_install:
        - make travis-setup
      script:
        - make integration-test-run
    - name: integration-test-layers
      before_install:
        - make travis-setup
      script:
        - make integration-test-layers
    - name: integration-test-misc
      before_install:
        - make travis-setup
      script:
        - make integration-test-misc
    - stage: build-images
      script:
        - make images
